export const exerciciosPadrao: { nome: string; categoria: string }[] = [
  // Peito
  { nome: 'Supino Reto (Barra)', categoria: 'Peito' },
  { nome: 'Supino Reto (Halteres)', categoria: 'Peito' },
  { nome: 'Supino Inclinado (Barra)', categoria: 'Peito' },
  { nome: 'Supino Inclinado (Halteres)', categoria: 'Peito' },
  { nome: 'Supino Declinado', categoria: 'Peito' },
  { nome: 'Supino Máquina', categoria: 'Peito' },
  { nome: 'Crucifixo Reto', categoria: 'Peito' },
  { nome: 'Crucifixo Inclinado', categoria: 'Peito' },
  { nome: 'Crossover (Polia Alta)', categoria: 'Peito' },
  { nome: 'Crossover (Polia Baixa)', categoria: 'Peito' },
  { nome: 'Peck Deck (Voador)', categoria: 'Peito' },
  { nome: 'Flexão de Braço', categoria: 'Peito' },
  { nome: 'Paralelas (Foco Peito)', categoria: 'Peito' },
  // Dorsal
  { nome: 'Puxada Alta (Pulldown) Aberta', categoria: 'Dorsal' },
  { nome: 'Puxada Alta (Pulldown) Fechada', categoria: 'Dorsal' },
  { nome: 'Puxada Triângulo', categoria: 'Dorsal' },
  { nome: 'Puxada Supinada', categoria: 'Dorsal' },
  { nome: 'Remada Curvada (Barra)', categoria: 'Dorsal' },
  { nome: 'Remada Curvada (Halteres)', categoria: 'Dorsal' },
  { nome: 'Remada Baixa (Cabo, Pegada Aberta)', categoria: 'Dorsal' },
  { nome: 'Remada Baixa (Cabo, Pegada Fechada)', categoria: 'Dorsal' },
  { nome: 'Remada Unilateral (Serrote)', categoria: 'Dorsal' },
  { nome: 'Remada Cavalinho (T-bar)', categoria: 'Dorsal' },
  { nome: 'Barra Fixa Pegada Aberta', categoria: 'Dorsal' },
  { nome: 'Barra Fixa Pegada Supinada', categoria: 'Dorsal' },
  { nome: 'Pulldown na Polia (Pull-down Reto)', categoria: 'Dorsal' },
  { nome: 'Levantamento Terra (foco lombar/dorsal)', categoria: 'Dorsal' },
  // Ombro
  { nome: 'Desenvolvimento Militar (Barra)', categoria: 'Ombro' },
  { nome: 'Desenvolvimento com Halteres', categoria: 'Ombro' },
  { nome: 'Desenvolvimento Arnold', categoria: 'Ombro' },
  { nome: 'Desenvolvimento Máquina', categoria: 'Ombro' },
  { nome: 'Elevação Lateral (Halteres)', categoria: 'Ombro' },
  { nome: 'Elevação Lateral (Polia)', categoria: 'Ombro' },
  { nome: 'Elevação Frontal (Halteres)', categoria: 'Ombro' },
  { nome: 'Elevação Frontal (Barra)', categoria: 'Ombro' },
  { nome: 'Remada Alta', categoria: 'Ombro' },
  { nome: 'Crucifixo Invertido (Halteres)', categoria: 'Ombro' },
  { nome: 'Crucifixo Invertido (Peck Deck)', categoria: 'Ombro' },
  { nome: 'Face Pull', categoria: 'Ombro' },
  { nome: 'Encolhimento de Ombros (Trapézio)', categoria: 'Ombro' },
  // Bíceps
  { nome: 'Rosca Direta (Barra)', categoria: 'Bíceps' },
  { nome: 'Rosca Direta (Halteres)', categoria: 'Bíceps' },
  { nome: 'Rosca Alternada', categoria: 'Bíceps' },
  { nome: 'Rosca Scott (Barra W)', categoria: 'Bíceps' },
  { nome: 'Rosca Martelo', categoria: 'Bíceps' },
  { nome: 'Rosca Cabo (Polia Baixa)', categoria: 'Bíceps' },
  { nome: 'Rosca Concentrada', categoria: 'Bíceps' },
  { nome: 'Rosca 21', categoria: 'Bíceps' },
  // Tríceps
  { nome: 'Tríceps Polia Alta (Pulley) — Barra', categoria: 'Tríceps' },
  { nome: 'Tríceps Polia Alta (Pulley) — Corda', categoria: 'Tríceps' },
  { nome: 'Tríceps Polia Baixa (Francês na Polia)', categoria: 'Tríceps' },
  { nome: 'Tríceps Testa (Barra)', categoria: 'Tríceps' },
  { nome: 'Tríceps Francês (Halter)', categoria: 'Tríceps' },
  { nome: 'Mergulho entre Bancos', categoria: 'Tríceps' },
  { nome: 'Mergulho nas Paralelas', categoria: 'Tríceps' },
  { nome: 'Coice de Tríceps (Halter)', categoria: 'Tríceps' },
  // Quadríceps
  { nome: 'Agachamento Livre', categoria: 'Quadríceps' },
  { nome: 'Agachamento Smith', categoria: 'Quadríceps' },
  { nome: 'Agachamento Frontal', categoria: 'Quadríceps' },
  { nome: 'Leg Press 45°', categoria: 'Quadríceps' },
  { nome: 'Leg Press Horizontal', categoria: 'Quadríceps' },
  { nome: 'Cadeira Extensora', categoria: 'Quadríceps' },
  { nome: 'Hack Machine', categoria: 'Quadríceps' },
  { nome: 'Afundo (Passada)', categoria: 'Quadríceps' },
  { nome: 'Avanço com Halteres', categoria: 'Quadríceps' },
  { nome: 'Cadeira Adutora', categoria: 'Quadríceps' },
  // Posterior de Coxa
  { nome: 'Stiff (Barra)', categoria: 'Posterior de Coxa' },
  { nome: 'Stiff (Halteres)', categoria: 'Posterior de Coxa' },
  { nome: 'Mesa Flexora', categoria: 'Posterior de Coxa' },
  { nome: 'Cadeira Flexora', categoria: 'Posterior de Coxa' },
  { nome: 'Flexora em Pé (Unilateral)', categoria: 'Posterior de Coxa' },
  { nome: 'Levantamento Terra Romeno', categoria: 'Posterior de Coxa' },
  { nome: 'Bom Dia (Good Morning)', categoria: 'Posterior de Coxa' },
  // Glúteo
  { nome: 'Elevação Pélvica (Hip Thrust)', categoria: 'Glúteo' },
  { nome: 'Hip Thrust na Máquina', categoria: 'Glúteo' },
  { nome: 'Glúteo no Cabo (Coice/Kickback)', categoria: 'Glúteo' },
  { nome: 'Abdução de Quadril (Cadeira Abdutora)', categoria: 'Glúteo' },
  { nome: 'Abdução no Cabo', categoria: 'Glúteo' },
  { nome: 'Agachamento Búlgaro', categoria: 'Glúteo' },
  { nome: 'Coice na Polia Baixa', categoria: 'Glúteo' },
  { nome: 'Passada com Foco em Glúteo', categoria: 'Glúteo' },
  // Abdômen
  { nome: 'Abdominal Supra (Solo)', categoria: 'Abdômen' },
  { nome: 'Abdominal Infra (Elevação de Pernas)', categoria: 'Abdômen' },
  { nome: 'Abdominal na Polia (Cable Crunch)', categoria: 'Abdômen' },
  { nome: 'Prancha Frontal', categoria: 'Abdômen' },
  { nome: 'Prancha Lateral', categoria: 'Abdômen' },
  { nome: 'Abdominal Oblíquo (Bicicleta)', categoria: 'Abdômen' },
  { nome: 'Abdominal na Máquina', categoria: 'Abdômen' },
  { nome: 'Elevação de Pernas na Barra', categoria: 'Abdômen' },
  { nome: 'Rotação de Tronco (Russian Twist)', categoria: 'Abdômen' },
  // Aeróbico
  { nome: 'Esteira (Caminhada/Corrida)', categoria: 'Aeróbico' },
  { nome: 'Bicicleta Ergométrica', categoria: 'Aeróbico' },
  { nome: 'Elíptico', categoria: 'Aeróbico' },
  { nome: 'Escada (StairMaster)', categoria: 'Aeróbico' },
  { nome: 'Remo Ergômetro', categoria: 'Aeróbico' },
  { nome: 'HIIT', categoria: 'Aeróbico' },
  { nome: 'Pular Corda', categoria: 'Aeróbico' },
  { nome: 'Bike Spinning', categoria: 'Aeróbico' },
]
